<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType Condition="'$(Configuration)' == 'Release'">WinExe</OutputType>
    <OutputType Condition="'$(Configuration)' == 'Debug'">Exe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ChzzkApi-CS" Version="0.1.2" />
    <PackageReference Include="Hexa.NET.ImGui" Version="2.2.9" />
    <PackageReference Include="Hexa.NET.ImGui.Backends" Version="1.0.18" />
    <PackageReference Include="Hexa.NET.ImGui.Backends.SDL3" Version="1.0.18" />
    <PackageReference Include="Hexa.NET.OpenGL3" Version="1.1.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4129.50" />
    <PackageReference Include="SDL3-CS" Version="3.4.2" />
    <PackageReference Include="SDL3-CS.Windows" Version="3.4.14.1" />
  </ItemGroup>
  
  <Target Name="GenerateThirdPartyNotices" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">
    <Exec Command="dotnet tool restore" WorkingDirectory="$(MSBuildProjectDirectory)" />
    <Exec Command="dotnet nuget-license -i &quot;$(MSBuildProjectFullPath)&quot; -t -d &quot;$(OutDir)licenses&quot; -o Table -fo &quot;$(OutDir)THIRD-PARTY-NOTICES.txt&quot;" WorkingDirectory="$(MSBuildProjectDirectory)" />
  </Target>
  
</Project>
